language: python
python:
  - "2.6"
  - "2.7"

before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -qq python-h5py

# command to install dependencies
install: 
 - "pip install -r requirements.txt"

# command to run tests
script:
 - "python setup.py install"
# - "python tests/testcomponent.py"
