language: python
python:
  - "2.6"
  - "2.7"

before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -qq libhdf5-serial-dev
 - sudo apt-get install -qq libatlas-dev libatlas-base-dev gfortran
 - sudo apt-get install -qq python-numpy python-scipy
 # Add Parisson packages repository for ubuntu precise and install TimeSide
 - sudo gpg --keyserver pgpkeys.mit.edu --recv-key E3298399DF14BB7C
 - sudo gpg -a --export E3298399DF14BB7C | sudo apt-key add -
 - sudo echo "deb http://debian.parisson.com/debian/ precise main" | \
    tee -a /etc/apt/sources.list.d/parisson.list
 - sudo echo "deb-src http://debian.parisson.com/debian/ precise main" | \
    tee -a /etc/apt/sources.list.d/parisson.list
  - sudo apt-get update
  - sudo apt-get install -y python-timeside



# command to install dependencies
#install: 
# - "pip install -r requirements.txt"

# command to run tests
script:
 - "python setup.py install"
# - "python tests/testcomponent.py"
